DEFAULT_ASSET_DIR = './assets'
DEFAULT_ASSETS_ONLY = False
DEFAULT_BASE_URL = 'http://exemple.com/soho/default-base-url'
DEFAULT_CONFIG_FILE = 'sohoconf.py'
DEFAULT_DO_NOTHING = False
DEFAULT_FORCE = False
DEFAULT_HIDE_INDEX_HTML = True
DEFAULT_IGNORE_FILES = ('.*\.DS_Store$', '.*~$')
DEFAULT_LOCALE_DIR = './locale'
DEFAULT_LOGGER_PATH = '-'
DEFAULT_LOGGER_LEVEL = 'info'
DEFAULT_OUT_DIR = './www'
DEFAULT_SRC_DIR = './src'
DEFAULT_SITEMAP = 'sitemap.xml'
DEFAULT_TEMPLATE_DIR = './templates'
